//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.NET.Sdk.Functions.MSBuild.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.NET.Sdk.Functions.MSBuild.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: &quot;7010fa61-d5df-46b5-a22e-98cfc81f1637&quot;,
        ///    &quot;status&quot;: 3,
        ///    &quot;status_text&quot;: &quot;&quot;,
        ///    &quot;author_email&quot;: &quot;N/A&quot;,
        ///    &quot;author&quot;: &quot;N/A&quot;,
        ///    &quot;deployer&quot;: &quot;Push-Deployer&quot;,
        ///    &quot;message&quot;: &quot;Created via a push deployment&quot;,
        ///    &quot;progress&quot;: &quot;&quot;,
        ///    &quot;received_time&quot;: &quot;2022-05-25T04:40:36.0994691Z&quot;,
        ///    &quot;start_time&quot;: &quot;2022-05-25T04:40:37.1272389Z&quot;,
        ///    &quot;end_time&quot;: &quot;2022-05-25T04:40:39.4733696Z&quot;,
        ///    &quot;last_success_end_time&quot;: null,
        ///    &quot;complete&quot;: true,
        ///    &quot;active&quot;: false,
        ///    &quot;is_temp&quot;: false,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeploymentResponse {
            get {
                return ResourceManager.GetString("DeploymentResponse", resourceCulture);
            }
        }
    }
}
