//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.NET.Sdk.Functions.MSBuild.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.NET.Sdk.Functions.MSBuild.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment status is {0}..
        /// </summary>
        internal static string DeploymentStatus {
            get {
                return ResourceManager.GetString("DeploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling for deployment status....
        /// </summary>
        internal static string DeploymentStatusPolling {
            get {
                return ResourceManager.GetString("DeploymentStatusPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither SiteName nor PublishUrl was given a value..
        /// </summary>
        internal static string NeitherSiteNameNorPublishUrlGivenError {
            get {
                return ResourceManager.GetString("NeitherSiteNameNorPublishUrlGivenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing {0} to {1}....
        /// </summary>
        internal static string PublishingZipViaZipDeploy {
            get {
                return ResourceManager.GetString("PublishingZipViaZipDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the deployment status....
        /// </summary>
        internal static string ZipDeployDeploymentStatus {
            get {
                return ResourceManager.GetString("ZipDeployDeploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt to publish the ZIP file through {0} failed with HTTP status code {1}..
        /// </summary>
        internal static string ZipDeployFailureErrorMessage {
            get {
                return ResourceManager.GetString("ZipDeployFailureErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Deployment failed. .
        /// </summary>
        internal static string ZipDeploymentFailed {
            get {
                return ResourceManager.GetString("ZipDeploymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Deployment succeeded..
        /// </summary>
        internal static string ZipDeploymentSucceeded {
            get {
                return ResourceManager.GetString("ZipDeploymentSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded the Zip file to the target..
        /// </summary>
        internal static string ZipFileUploaded {
            get {
                return ResourceManager.GetString("ZipFileUploaded", resourceCulture);
            }
        }
    }
}
