# This build is used for public PR and CI builds.

name: $(Build.SourceBranchName)_$(Build.Reason)_$(BuildNumber)

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - v3.x

schedules:
  # Ensure we build nightly to catch any new CVEs and report SDL often.
  - cron: "0 3 * * *"
    displayName: Nightly Build
    branches:
      include:
      - main
      - release/*
      - v3.x
    always: true

pr:
  branches:
    include:
    - main
    - release/*
    - v3.x

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - template: /eng/ci/templates/variables/build.yml@self

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
      ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
        demands:
        - Priority -equals Low

    sdl:
      codeql:
        compiled:
          enabled: true
        runSourceLanguagesInSourceAnalysis: true
      autobaseline:
        enableForGitHub: true

    featureFlags:
      autoBaseline: true

    settings:
      # PR's from forks do not have sufficient permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}

    stages:
    - stage: Build
      jobs:
      - template: /eng/ci/templates/jobs/build-and-test.yml@self
        parameters:
          SkipBuildArtifacts: true
