jobs:
- job: RunTests
  displayName: Run tests

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022
    os: windows

  steps:
  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Unit Tests
    inputs:
      command: test
      projects: |
        **\Microsoft.NET.Sdk.Functions.Generator.Tests.csproj
        **\Microsoft.NET.Sdk.Functions.MSBuild.Tests.csproj
        **\Microsoft.NET.Sdk.Functions.EndToEnd.Tests.csproj

  - task: DotNetCoreCLI@2
    displayName: End to End tests
    inputs:
      command: test
      projects: |
        **\FunctionsSdkE2ETests\FunctionsSdkE2ETests.sln
      arguments: -v n
